export const EXCURSIONS = [
  // Nature
  { id: 'dunns-river-falls', title: "Dunn's River Falls", category: 'Nature', location: 'Ocho Rios', duration: '3 hrs', times: '8:30 AM', resortAreas: ['Ocho Rios', 'Runaway Bay', 'Falmouth'], image: 'assets/images/jamaica-falls.jpg', summary: 'Guided waterfall climb plus beach access at Jamaica\'s iconic falls.', includes: ['Private transport from hotel', 'Licensed local guide', '24/7 WhatsApp support', 'Safe return drop-off'], excludes: ['Admission fee (~$20 USD)', 'Water shoes (recommended)', 'Food & drinks', 'Tips'] },
  { id: 'blue-hole-secret-falls', title: 'Blue Hole (Secret Falls / Island Gully)', category: 'Nature', location: 'St. Ann', duration: '3 hrs', times: '8:30 AM', resortAreas: ['Ocho Rios', 'Runaway Bay'], image: 'assets/images/jamaica-mayfield.jpg', summary: 'Blue spring pools, rope swings, and rainforest cascades.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$20 USD)', 'Food & drinks', 'Tips'] },
  { id: 'ys-falls', title: 'YS Falls', category: 'Nature', location: 'St. Elizabeth', duration: '4 hrs', times: '7:30 AM', resortAreas: ['Negril', 'Montego Bay'], image: 'assets/images/jamaica-mayfield.jpg', summary: 'Seven-tier waterfall gardens with natural pools and canopy zipline.', includes: ['Private transport', 'Licensed guide', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$25 USD)', 'Zipline add-on (optional)', 'Food & drinks'] },
  { id: 'reach-falls', title: 'Reach Falls', category: 'Nature', location: 'Portland', duration: '4 hrs', times: '7:00 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'River cave and jungle waterfall adventure in eastern Jamaica.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$15 USD)', 'Food & drinks', 'Tips'] },
  { id: 'green-grotto-caves', title: 'Green Grotto Caves', category: 'Nature', location: 'Discovery Bay', duration: '2 hrs', times: '9:00 AM', resortAreas: ['Runaway Bay', 'Ocho Rios', 'Montego Bay'], image: 'assets/images/jamaica-culture.jpg', summary: 'Historic limestone cave network with underground lake.', includes: ['Private transport', 'Licensed guide', '24/7 WhatsApp support'], excludes: ['Admission fee (~$20 USD)', 'Food & drinks'] },
  { id: 'blue-mountains-tour', title: 'Blue Mountains (hiking + coffee tours)', category: 'Nature', location: 'St. Andrew', duration: 'Full Day', times: '6:30 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Sunrise trails and origin coffee tastings above Kingston.', includes: ['Private transport', 'Expert hiking guide', 'Coffee tasting session', '24/7 WhatsApp support'], excludes: ['Entrance fees', 'Meals', 'Tips'] },
  { id: 'cockpit-country', title: 'Cockpit Country', category: 'Nature', location: 'Trelawny', duration: 'Full Day', times: '7:00 AM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-transfer.jpg', summary: 'Karst valleys, endemic wildlife, and expert local nature guiding.', includes: ['Private transport', 'Specialist nature guide', '24/7 WhatsApp support'], excludes: ['Park fees', 'Meals', 'Tips'] },
  { id: 'black-river-safari', title: 'Black River Safari Tour', category: 'Nature', location: 'St. Elizabeth', duration: '3 hrs', times: '8:30 AM', resortAreas: ['Negril', 'Montego Bay'], image: 'assets/images/jamaica-river-rafting.jpg', summary: 'Boat safari through mangroves and crocodile habitat.', includes: ['Private transport', 'Boat tour', 'Narrated wildlife guide', '24/7 WhatsApp support'], excludes: ['Food & drinks', 'Tips'] },
  { id: 'martha-brae-rafting', title: 'Martha Brae River bamboo rafting', category: 'Nature', location: 'Trelawny', duration: '2 hrs', times: '9:00 AM', resortAreas: ['Montego Bay', 'Falmouth', 'Ocho Rios'], image: 'assets/images/jamaica-bamboo-rafting-guests.jpg', summary: 'Slow scenic bamboo rafting with local raft captain.', includes: ['Private transport', 'Bamboo raft ride', 'Raft captain', '24/7 WhatsApp support'], excludes: ['Rafting admission (~$75 USD)', 'Food & drinks', 'Tips'] },
  { id: 'rio-grande-rafting', title: 'Rio Grande River rafting', category: 'Nature', location: 'Portland', duration: '3-4 hrs', times: '8:00 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-falls.jpg', summary: 'Long-form bamboo raft journey through lush Portland valleys.', includes: ['Private transport', 'Raft captain', '24/7 WhatsApp support'], excludes: ['Rafting fee', 'Food & drinks', 'Tips'] },

  // Beach
  { id: 'seven-mile-beach', title: 'Seven Mile Beach', category: 'Beach', location: 'Negril', duration: 'Full Day', times: '8:00 AM', resortAreas: ['Negril', 'Montego Bay'], image: 'assets/images/jamaica-beach.jpg', summary: 'White-sand stretch, calm clear water, and sunset energy.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Beach entry (varies)', 'Food & drinks', 'Watersports add-ons'] },
  { id: 'doctors-cave-beach', title: "Doctor's Cave Beach", category: 'Beach', location: 'Montego Bay', duration: 'Half Day', times: '9:00 AM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-lagoon-sunset.jpg', summary: 'Classic Mobay beach club known for turquoise calm water.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Admission (~$6 USD)', 'Food & drinks', 'Chair rental'] },
  { id: 'frenchmans-cove', title: "Frenchman's Cove", category: 'Beach', location: 'Portland', duration: 'Half Day', times: '8:30 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'River-meets-sea cove framed by tropical greenery.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$15 USD)', 'Food & drinks'] },
  { id: 'boston-bay-beach', title: 'Boston Bay Beach', category: 'Beach', location: 'Portland', duration: 'Half Day', times: '9:00 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-river-rafting.jpg', summary: 'Surf-friendly bay near Jamaica\'s jerk heartland.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Beach is free', 'Food & drinks (jerk nearby)', 'Tips'] },
  { id: 'winnifred-beach', title: 'Winnifred Beach', category: 'Beach', location: 'Portland', duration: 'Half Day', times: '9:00 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-beach.jpg', summary: 'Community-loved beach with authentic local vibe.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Beach is free (public)', 'Food & drinks', 'Tips'] },
  { id: 'hellshire-beach', title: 'Hellshire Beach', category: 'Beach', location: 'St. Catherine', duration: 'Half Day', times: '9:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-pelican-bar.jpg', summary: 'Popular fish beach with local weekend atmosphere.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Parking fee', 'Fresh fish & food', 'Tips'] },
  { id: 'james-bond-beach', title: 'James Bond Beach', category: 'Beach', location: 'St. Mary', duration: 'Half Day', times: '9:00 AM', resortAreas: ['Ocho Rios'], image: 'assets/images/jamaica-beach.jpg', summary: 'North-coast beach spot tied to Bond film lore.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$10 USD)', 'Food & drinks', 'Watersports'] },

  // Culture
  { id: 'bob-marley-museum', title: 'Bob Marley Museum', category: 'Culture', location: 'Kingston', duration: '2 hrs', times: '9:30 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-bob-marley-statue.jpg', summary: 'Walk through 56 Hope Road and reggae history.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Museum admission (~$35 USD)', 'Photos inside (ask guide)', 'Tips'] },
  { id: 'devon-house', title: 'Devon House', category: 'Culture', location: 'Kingston', duration: '2 hrs', times: '10:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-culture.jpg', summary: 'Historic mansion, courtyard food, and island heritage.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Mansion tour fee', 'Ice cream (must-try!)', 'Tips'] },
  { id: 'rose-hall-great-house', title: 'Rose Hall Great House (haunted night tour)', category: 'Culture', location: 'Montego Bay', duration: '2 hrs', times: '7:00 PM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Legendary Georgian estate with night storytelling tour.', includes: ['Private transport', 'Night return', '24/7 WhatsApp support'], excludes: ['Admission fee (~$25 USD)', 'Food & drinks', 'Tips'] },
  { id: 'accompong-maroon-village', title: 'Accompong Maroon Village', category: 'Culture', location: 'St. Elizabeth', duration: 'Full Day', times: '7:30 AM', resortAreas: ['Negril', 'Montego Bay'], image: 'assets/images/jamaica-carnival.jpg', summary: 'Maroon history, drumming, and indigenous heritage.', includes: ['Private transport', 'Village guide', 'Cultural ceremony access', '24/7 WhatsApp support'], excludes: ['Village fee', 'Meals', 'Tips'] },
  { id: 'rastafari-indigenous-village', title: 'Rastafari Indigenous Village', category: 'Culture', location: 'Montego Bay', duration: '3 hrs', times: '9:30 AM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-culture.jpg', summary: 'Roots culture immersion with drumming and ital traditions.', includes: ['Private transport', 'Cultural host', '24/7 WhatsApp support'], excludes: ['Village entrance fee', 'Ital meal (optional, on-site)', 'Tips'] },
  { id: 'falmouth-historic-district', title: 'Falmouth Historic District', category: 'Culture', location: 'Trelawny', duration: '2 hrs', times: '9:00 AM', resortAreas: ['Falmouth', 'Montego Bay', 'Ocho Rios'], image: 'assets/images/jamaica-transfer.jpg', summary: 'Georgian port-town architecture and guided heritage walk.', includes: ['Private transport', 'Licensed heritage guide', '24/7 WhatsApp support'], excludes: ['Selected site fees', 'Food & drinks', 'Tips'] },
  { id: 'port-royal', title: 'Port Royal', category: 'Culture', location: 'Kingston', duration: '2 hrs', times: '9:30 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-lagoon-sunset.jpg', summary: 'Historic pirate city and maritime fort history.', includes: ['Private transport', 'Local guide', 'Fort Charles access', '24/7 WhatsApp support'], excludes: ['Fort admission (~$10 USD)', 'Food & drinks', 'Tips'] },

  // Food
  { id: 'scotchies', title: 'Scotchies (jerk chicken/pork)', category: 'Food', location: 'Montego Bay', duration: '2 hrs', times: '11:30 AM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-food.jpg', summary: 'Legendary jerk stop with pimento-wood smoke flavor.', includes: ['Private transport', 'Local food guide', '24/7 WhatsApp support'], excludes: ['Food & drinks (your choice)', 'Tips'] },
  { id: 'ricks-cafe-dining', title: "Rick's Cafe (sunset + cliff diving + dining)", category: 'Food', location: 'Negril', duration: '3 hrs', times: '4:00 PM', resortAreas: ['Negril'], image: 'assets/images/jamaica-lagoon-sunset.jpg', summary: 'Sunset dining with iconic cliff-diving scene.', includes: ['Private transport', 'Evening return', '24/7 WhatsApp support'], excludes: ['Food & drinks', 'Entry fee on event nights', 'Tips'] },
  { id: 'boston-jerk-centre', title: 'Boston Jerk Centre', category: 'Food', location: 'Portland', duration: '2 hrs', times: '11:00 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-food.jpg', summary: 'Original jerk corridor with authentic pit cooking.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Food & drinks', 'Tips'] },
  { id: 'glorias-seafood', title: "Gloria's Seafood", category: 'Food', location: 'Kingston', duration: '2 hrs', times: '12:00 PM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-pelican-bar.jpg', summary: 'Local seafood institution with waterfront energy.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Food & drinks', 'Tips'] },
  { id: 'kingston-street-food-flavours', title: 'Kingston Street Food & Flavours', category: 'Food', location: 'Kingston', duration: '3 hrs', times: '11:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-food.jpg', summary: 'Curated tasting route through Kingston favorites, from jerk to patties.', includes: ['Private transport', 'Local food guide', 'Tasting route map', '24/7 WhatsApp support'], excludes: ['Food costs (budget ~$20-30 USD)', 'Tips'] },
  { id: 'appleton-estate', title: 'Appleton Estate rum tours', category: 'Food', location: 'St. Elizabeth', duration: '4 hrs', times: '9:00 AM', resortAreas: ['Negril', 'Montego Bay'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Estate-to-glass rum heritage tour and tasting.', includes: ['Private transport', 'Estate tour', 'Rum tasting session', '24/7 WhatsApp support'], excludes: ['Estate admission (~$30 USD)', 'Additional bottles', 'Tips'] },
  { id: 'sweetwood-jerk-joint', title: 'Sweetwood Jerk Joint', category: 'Food', location: 'Kingston', duration: '2 hrs', times: '12:00 PM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-food.jpg', summary: 'Fast local favorite for jerk and sides.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Food & drinks', 'Tips'] },
  { id: 'tracks-and-records', title: "Usain Bolt's Tracks & Records", category: 'Food', location: 'Kingston', duration: '2 hrs', times: '7:00 PM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-concert.jpg', summary: 'Sports bar dining with nightlife crossover.', includes: ['Private transport', 'Evening return', '24/7 WhatsApp support'], excludes: ['Food & drinks', 'Entry on event nights', 'Tips'] },

  // Adventure
  { id: 'mystic-mountain', title: 'Mystic Mountain (zipline + bobsled)', category: 'Adventure', location: 'Ocho Rios', duration: '3 hrs', times: '9:00 AM', resortAreas: ['Ocho Rios', 'Runaway Bay', 'Falmouth'], image: 'assets/images/jamaica-mystic.jpg', summary: 'Bobsled, zipline, and chairlift in rainforest terrain.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Admission + attractions (~$60-80 USD)', 'Food & drinks', 'Locker rental'] },
  { id: 'chukka-caribbean', title: 'Chukka Caribbean Adventures (ATV, zipline, horseback)', category: 'Adventure', location: 'Multiple parishes', duration: 'Half Day', times: '8:30 AM', resortAreas: ['Montego Bay', 'Ocho Rios', 'Negril'], image: 'assets/images/jamaica-horseback-riding.jpg', summary: 'High-adrenaline bundles across land and trail routes.', includes: ['Private transport', 'Licensed activity guides', '24/7 WhatsApp support'], excludes: ['Activity fees (~$60-120 USD)', 'Food & drinks', 'Tips'] },
  { id: 'dolphin-cove-adventure', title: 'Dolphin Cove', category: 'Adventure', location: 'Ocho Rios', duration: '3 hrs', times: '9:30 AM', resortAreas: ['Ocho Rios', 'Runaway Bay'], image: 'assets/images/jamaica-beach.jpg', summary: 'Marine interaction park with added activity options.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Admission + dolphin interaction (~$70-130 USD)', 'Food & drinks'] },
  { id: 'yaaman-adventure-park', title: 'Yaaman Adventure Park', category: 'Adventure', location: 'Ocho Rios', duration: '3 hrs', times: '9:00 AM', resortAreas: ['Ocho Rios', 'Runaway Bay'], image: 'assets/images/jamaica-mystic.jpg', summary: 'ATV rides, mud tracks, and Jamaican cooking moments.', includes: ['Private transport', 'Activity guide', '24/7 WhatsApp support'], excludes: ['Admission (~$60-90 USD)', 'Food & drinks', 'Tips'] },
  { id: 'blue-hole-mineral-spring', title: 'Blue Hole Mineral Spring', category: 'Adventure', location: 'Negril', duration: '2 hrs', times: '10:00 AM', resortAreas: ['Negril'], image: 'assets/images/jamaica-lagoon-sunset.jpg', summary: 'Mineral spring cave jump and countryside views.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Entry fee (~$15 USD)', 'Food & drinks', 'Tips'] },
  { id: 'luminous-lagoon-swim', title: 'Luminous Lagoon night glow swim', category: 'Adventure', location: 'Falmouth', duration: '2 hrs', times: '8:30 PM', resortAreas: ['Falmouth', 'Montego Bay', 'Ocho Rios'], image: 'assets/images/glistening-waters-falmouth.jpg', summary: 'Night swim where the water glows with movement.', includes: ['Private transport', 'Night return', 'Boat tour', '24/7 WhatsApp support'], excludes: ['Tour fee (~$25-35 USD)', 'Towel', 'Tips'] },
  { id: 'negril-cliffs-diving', title: 'Negril Cliffs cliff diving', category: 'Adventure', location: 'Negril', duration: '3 hrs', times: '4:30 PM', resortAreas: ['Negril'], image: 'assets/images/jamaica-beach.jpg', summary: 'Cliff-side viewing and optional guided jump zones.', includes: ['Private transport', 'Local guide', 'Sunset return', '24/7 WhatsApp support'], excludes: ['Food & drinks at cliff bars', 'Tips'] },

  // Luxury
  { id: 'private-yacht-mobay', title: 'Private yacht charter - Montego Bay Marine Park', category: 'Luxury', location: 'Montego Bay', duration: '4 hrs', times: '10:00 AM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-pelican-bar.jpg', summary: 'Private vessel charter with custom onboard itinerary.', includes: ['Private transport to marina', 'Luxury yacht charter', 'Captain & crew', 'Snorkeling equipment', '24/7 WhatsApp support'], excludes: ['Food & drinks (BYO or provisioned on request)', 'Tips for crew'] },
  { id: 'helicopter-island-tour', title: 'Helicopter tours (island aerial views)', category: 'Luxury', location: 'Island-wide', duration: '1 hr', times: 'Flexible', resortAreas: ['Montego Bay', 'Ocho Rios', 'Negril', 'Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Aerial Jamaica circuit for premium travelers.', includes: ['Private airport transport', 'Helicopter tour', 'Aerial guide', '24/7 WhatsApp support'], excludes: ['Helicopter fee (quoted separately)', 'Tips'] },
  { id: 'tryall-roundhill-villas', title: 'Private villas in Tryall Club / Round Hill', category: 'Luxury', location: 'Montego Bay', duration: 'Custom', times: 'On request', resortAreas: ['Montego Bay'], image: 'assets/images/jamaica-beach.jpg', summary: 'Private-villa transfer and concierge coordination.', includes: ['Private luxury vehicle', 'Door-to-door service', 'Concierge coordination', '24/7 WhatsApp support'], excludes: ['Villa rental cost', 'Grocery provisioning', 'Tips'] },
  { id: 'taboo-nightclub-vip', title: 'VIP nightlife: Taboo Nightclub', category: 'Luxury', location: 'Montego Bay', duration: 'Night', times: '9:00 PM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-concert.jpg', summary: 'VIP nightlife routing with private transport.', includes: ['Private night transport', 'Safe 3 AM return guaranteed', '24/7 WhatsApp support'], excludes: ['Entry & VIP table fees', 'Food & drinks', 'Tips'] },
  { id: 'strawberry-hill-spa', title: 'Spa day: Strawberry Hill Spa', category: 'Luxury', location: 'Blue Mountains', duration: 'Half Day', times: '9:30 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Mountain wellness retreat and scenic spa experiences.', includes: ['Private transport to Blue Mountains', 'Scenic route guidance', '24/7 WhatsApp support'], excludes: ['Spa treatment fees (~$80-200 USD)', 'Meals at resort', 'Tips'] },
  { id: 'pelican-bar-sunset-boat-trip', title: 'Pelican Bar Sunset Boat Trip', category: 'Luxury', location: 'St. Elizabeth', duration: '5 hrs', times: '1:00 PM', resortAreas: ['Negril', 'Montego Bay'], image: 'assets/images/jamaica-pelican-bar.jpg', summary: 'Sandbar bar sunset trip with private boat options and photo stops.', includes: ['Private transport', 'Boat charter to Pelican Bar', 'Sunset return', '24/7 WhatsApp support'], excludes: ['Food & drinks at Pelican Bar', 'Tips for boat captain'] },

  // Hidden Gems
  { id: 'somerset-falls', title: 'Somerset Falls', category: 'Hidden Gems', location: 'Portland', duration: '3 hrs', times: '8:30 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-falls.jpg', summary: 'Boat-in grotto waterfall and quiet tropical gardens.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$20 USD)', 'Food & drinks', 'Tips'] },
  { id: 'konoko-falls', title: 'Konoko Falls', category: 'Hidden Gems', location: 'Ocho Rios', duration: '2 hrs', times: '9:00 AM', resortAreas: ['Ocho Rios', 'Runaway Bay'], image: 'assets/images/jamaica-mayfield.jpg', summary: 'Terraced falls and botanical trails with fewer crowds.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$15 USD)', 'Food & drinks', 'Tips'] },
  { id: 'reggae-falls', title: 'Reggae Falls', category: 'Hidden Gems', location: 'St. Thomas', duration: '3 hrs', times: '8:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Natural falls with local countryside atmosphere.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Small entry donation', 'Food & drinks', 'Tips'] },
  { id: 'cane-river-falls', title: 'Cane River Falls', category: 'Hidden Gems', location: 'St. Andrew', duration: '2 hrs', times: '9:30 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-river-rafting.jpg', summary: 'Off-path waterfall spot ideal for private moments.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Small entry fee', 'Food & drinks', 'Tips'] },
  { id: 'lovers-leap', title: 'Lovers Leap', category: 'Hidden Gems', location: 'St. Elizabeth', duration: '2 hrs', times: '9:30 AM', resortAreas: ['Negril', 'Montego Bay'], image: 'assets/images/jamaica-lagoon-sunset.jpg', summary: 'South-coast cliff viewpoint with dramatic sea panoramas.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Entrance fee (~$5 USD)', 'Food & drinks', 'Tips'] },
  { id: 'milk-river-bath', title: 'Milk River Bath', category: 'Hidden Gems', location: 'Clarendon', duration: '2 hrs', times: '10:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-transfer.jpg', summary: 'Mineral-rich thermal bath destination with local history.', includes: ['Private transport', 'Local guide', '24/7 WhatsApp support'], excludes: ['Bath admission fee', 'Towel', 'Tips'] },

  // Accessible
  { id: 'emancipation-park', title: 'Emancipation Park (flat + accessible)', category: 'Accessible', location: 'Kingston', duration: '2 hrs', times: '9:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-culture.jpg', summary: 'Smooth pathways and city-center accessible leisure route.', includes: ['Wheelchair-accessible vehicle', 'Accessible route guide', 'Step assistance', '24/7 WhatsApp support'], excludes: ['Park is free', 'Food & drinks', 'Tips'] },
  { id: 'hope-botanical-gardens', title: 'Hope Botanical Gardens', category: 'Accessible', location: 'Kingston', duration: '2 hrs', times: '9:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-mayfield.jpg', summary: 'Mobility-friendly garden paths and shaded open grounds.', includes: ['Wheelchair-accessible vehicle', 'Accessible guide', 'Step assistance', '24/7 WhatsApp support'], excludes: ['Entrance is free', 'Food & drinks', 'Tips'] },
  { id: 'blue-mountain-scenic-drive', title: 'Scenic Blue Mountain drive (no hike option)', category: 'Accessible', location: 'St. Andrew', duration: 'Half Day', times: '8:30 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'View-heavy mountain route with minimal walking required.', includes: ['Private accessible vehicle', 'Scenic stops pre-selected', 'Step assistance', '24/7 WhatsApp support'], excludes: ['Coffee tasting add-on (optional)', 'Meals', 'Tips'] },
  { id: 'doctors-cave-private-setup', title: "Private beach setups at Doctor's Cave", category: 'Accessible', location: 'Montego Bay', duration: 'Half Day', times: '9:00 AM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-beach.jpg', summary: 'Assisted setup for accessible beach comfort and shade.', includes: ['Accessible vehicle', 'Chair setup coordination', 'Beach call-ahead', 'Step assistance', '24/7 WhatsApp support'], excludes: ['Admission (~$6 USD)', 'Shade chair rental', 'Food & drinks'] },

  // Family
  { id: 'kool-runnings-water-park', title: 'Kool Runnings Water Park', category: 'Family', location: 'Negril', duration: 'Half Day', times: '10:00 AM', resortAreas: ['Negril'], image: 'assets/images/jamaica-mystic.jpg', summary: 'Slides, pools, and family-safe water fun.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Admission (~$30-50 USD per person)', 'Food & drinks', 'Lockers'] },
  { id: 'hope-zoo', title: 'Hope Zoo', category: 'Family', location: 'Kingston', duration: '2 hrs', times: '10:00 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-culture-tour-group.jpg', summary: 'Kid-friendly wildlife visit inside Hope Gardens area.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Admission (~$10 USD)', 'Food & drinks', 'Tips'] },
  { id: 'dolphin-cove-family', title: 'Dolphin Cove', category: 'Family', location: 'Ocho Rios', duration: '3 hrs', times: '9:30 AM', resortAreas: ['Ocho Rios', 'Runaway Bay'], image: 'assets/images/jamaica-beach.jpg', summary: 'Family marine interaction packages with guided support.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Admission + interaction fees (~$70-130 USD)', 'Food & drinks'] },
  { id: 'mystic-mountain-family', title: 'Mystic Mountain', category: 'Family', location: 'Ocho Rios', duration: '3 hrs', times: '9:00 AM', resortAreas: ['Ocho Rios', 'Runaway Bay', 'Falmouth'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Rainforest rides and activities for mixed-age groups.', includes: ['Private transport', 'Return pickup', '24/7 WhatsApp support'], excludes: ['Admission + attractions (~$60-80 USD)', 'Food & drinks'] },

  // Couples
  { id: 'sunset-cruise-mobay', title: 'Sunset cruise in Montego Bay', category: 'Couples', location: 'Montego Bay', duration: '2 hrs', times: '5:30 PM', resortAreas: ['Montego Bay', 'Falmouth'], image: 'assets/images/jamaica-lagoon-sunset.jpg', summary: 'Golden-hour cruise with private or shared options.', includes: ['Private transport to marina', 'Cruise ticket', 'Sunset return', '24/7 WhatsApp support'], excludes: ['Drinks on cruise (some included — ask)', 'Tips for crew'] },
  { id: 'caves-restaurant-dinner', title: 'Private dinner at The Caves Restaurant', category: 'Couples', location: 'Negril', duration: 'Evening', times: '6:30 PM', resortAreas: ['Negril'], image: 'assets/images/jamaica-beach.jpg', summary: 'Romantic cliffside dinner transfer and timing service.', includes: ['Private transport', 'Evening return', 'Reservation coordination', '24/7 WhatsApp support'], excludes: ['Dinner bill', 'Tips'] },
  { id: 'blue-lagoon-romance', title: 'Blue Lagoon romance tour', category: 'Couples', location: 'Portland', duration: 'Half Day', times: '8:30 AM', resortAreas: ['Ocho Rios', 'Kingston'], image: 'assets/images/jamaica-luminous-lagoon-trelawny.jpg', summary: 'Private lagoon route built for scenic romantic pacing.', includes: ['Private transport', 'Boat access', 'Romantic route guide', '24/7 WhatsApp support'], excludes: ['Boat fee', 'Picnic food (on request)', 'Tips'] },
  { id: 'strawberry-hill-retreat', title: 'Spa + retreat at Strawberry Hill', category: 'Couples', location: 'Blue Mountains', duration: 'Half Day', times: '9:30 AM', resortAreas: ['Kingston'], image: 'assets/images/jamaica-mountains.jpg', summary: 'Spa and mountain retreat for honeymoon-style days.', includes: ['Private transport', 'Scenic Blue Mountain route', 'Reservation coordination', '24/7 WhatsApp support'], excludes: ['Spa treatments (~$80-200 USD each)', 'Meals', 'Tips'] }
];

export const CATEGORY_ORDER = [
  'Nature',
  'Beach',
  'Culture',
  'Food',
  'Adventure',
  'Luxury',
  'Hidden Gems',
  'Accessible',
  'Family',
  'Couples'
];

export const RESORT_AREAS = [
  'Montego Bay',
  'Ocho Rios',
  'Negril',
  'Falmouth',
  'Runaway Bay',
  'Kingston',
  'Port Antonio'
];

export function getExcursionById(id) {
  return EXCURSIONS.find(item => item.id === id);
}

export function getExcursionsByCategory(category) {
  return EXCURSIONS.filter(item => item.category === category);
}

export function getExcursionsByResortArea(resortArea) {
  return EXCURSIONS.filter(item => item.resortAreas && item.resortAreas.includes(resortArea));
}
